spring.mvc.favicon.enabled: false
spring.data.rest.base-path: /data
cineglobe.ide.home: ${user.home}/cineglobe-home
cineglobe.ide.initialize-home: false

milton.filesystemroot: ${cineglobe.ide.home}

spring.jpa.hibernate.ddl-auto: create
spring.datasource.url: jdbc:mysql://localhost:3306/playardb
spring.datasource.username: cineglobe
spring.datasource.password: c1n3gl0b3